main:
  - name: Home
    url: /
    weight: 10

  - name: Quiénes somos
    url: /quienes-somos/
    weight: 20

  - name: Qué hacemos
    url: /que-hacemos/
    weight: 30

  - name: Blog
    url: https://www.metadocencia.org/post/
    weight: 40
