# === Header ===
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "MetaDocencia"
    button:
      enable: true
      text: "Join us"
      url: "en/cta/"
    show_search: true
    show_theme_chooser: true

footer:
  enable: true
  show_translucent: false
  lines:
    - 'MetaDocencia is a fiscally sponsored project of <a href="https://www.codeforsociety.org/" target="_blank" rel="noopener">Code for Science &amp; Society</a>.'
    - 'Published with <a href="https://hugoblox.com/" target="_blank" rel="noopener">Hugo Blox</a>.'
    - |
      <div class="mdnv-footer-grid">
        <div class="mdnv-footer-left"><!-- Si querés, podés agregar más enlaces a la izquierda --></div>
        <nav class="mdnv-footer-right" aria-label="Legal links">
          <a href="https://zenodo.org/records/12534196" target="_blank" rel="noopener">Code of Conduct</a>
          <a href="https://zenodo.org/records/10514982" target="_blank" rel="noopener">Accessibility Policy</a>
          <a href="https://mdnv.netlify.app/en/licence/" >License</a>
        </nav>
      </div>
  link_items: []   # Vacío para no duplicar enlaces

