# === Header ===
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "MetaDocencia"
    button:
      enable: true
      text: "Join us"
      url: "en/cta/"
    show_search: true
    show_theme_chooser: true

footer:
  enable: true
  show_translucent: false
  lines:
    - |
      <div class="mdnv-footer-grid">
        <div class="mdnv-footer-left">
          <p>MetaDocencia is a fiscally sponsored project of <a href="https://www.codeforsociety.org/" target="_blank" rel="noopener">Code for Science &amp; Society</a>.</p>
          <p>Published with <a href="https://hugoblox.com/" target="_blank" rel="noopener">Hugo Blox</a>.</p>
        </div>
        <nav class="mdnv-footer-right" aria-label="Legal links">
          <a href="https://zenodo.org/records/13236270" target="_blank" rel="noopener">Community Guidelines</a>
          <a href="https://zenodo.org/records/10514982" target="_blank" rel="noopener">Accessibility Policy</a>
          <a href="/en/licence/">License</a>
        </nav>
      </div>
  link_items: []   # vacío para no duplicar


