/* Footer: 2 columnas, con los 3 últimos links a la derecha */
.site-footer .footer-links {
  display: grid;
  grid-template-columns: 1fr auto;         /* izquierda flexible, derecha ajustada */
  align-items: start;
  gap: 0.35rem 2rem;                        /* espacio entre filas/columnas */
}

/* Por defecto, todos a la columna izquierda */
.site-footer .footer-links > a {
  grid-column: 1;
}

/* Los 3 últimos enlaces (License, Code of Conduct, Accessibility Policy) a la derecha */
.site-footer .footer-links > a:nth-last-child(3),
.site-footer .footer-links > a:nth-last-child(2),
.site-footer .footer-links > a:nth-last-child(1) {
  grid-column: 2;
  justify-self: end;                        /* alinea a la derecha dentro de la col derecha */
  display: block;
}

/* En pantallas chicas: una sola columna, todo a la izquierda */
@media (max-width: 768px) {
  .site-footer .footer-links {
    grid-template-columns: 1fr;
    gap: 0.35rem 0;
  }
  .site-footer .footer-links > a,
  .site-footer .footer-links > a:nth-last-child(3),
  .site-footer .footer-links > a:nth-last-child(2),
  .site-footer .footer-links > a:nth-last-child(1) {
    grid-column: 1 !important;
    justify-self: start;
  }
}
