# netlify.toml — MD (seguro para PR/branches)

[build]
  command = "echo HUGO_BASEURL=$HUGO_BASEURL && pnpm install && hugo --gc --minify -b \"$HUGO_BASEURL\" && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  NODE_VERSION = "20.0.0"
  HUGO_ENABLEGITINFO = "true"

############################################
# Producción (www)
############################################
[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://www.metadocencia.org/"

# (Opcional) Redirecciones SOLO en producción
[context.production]
  # Ejemplo: apex -> www si lo tenías en redirects (si ya lo manejás en "Domain management", podés omitir)
  [[context.production.redirects]]
    from = "https://metadocencia.org/*"
    to = "https://www.metadocencia.org/:splat"
    status = 301
    force = true

  # Otros 301 que necesites, también aquí dentro, uno por uno:
  # [[context.production.redirects]]
  #   from = "/blog/*"
  #   to = "/post/:splat"
  #   status = 301

############################################
# Deploy previews (PRs)
############################################
[context.deploy-preview]
  command = "echo HUGO_BASEURL=$HUGO_BASEURL && pnpm install && hugo --gc --minify --buildFuture -b \"$HUGO_BASEURL\" && npx pagefind --source 'public'"

[context.deploy-preview.environment]
  HUGO_BASEURL = "$DEPLOY_PRIME_URL/"

############################################
# Branch deploys (main, staging, etc.)
############################################
[context.branch-deploy]
  command = "echo HUGO_BASEURL=$HUGO_BASEURL && pnpm install && hugo --gc --minify -b \"$HUGO_BASEURL\" && npx pagefind --source 'public'"

[context.branch-deploy.environment]
  HUGO_BASEURL = "$DEPLOY_PRIME_URL/"

############################################
# Plugins
############################################
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
