# netlify.toml — MetaDocencia

[build]
  # Siempre pasamos el baseURL explícito desde HUGO_BASEURL
  command = "pnpm install && hugo --gc --minify -b \"$HUGO_BASEURL\" && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  NODE_VERSION = "20.0.0"
  HUGO_ENABLEGITINFO = "true"

############################################
# Producción (www.metadocencia.org)
############################################
[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://www.metadocencia.org/"

############################################
# Deploy previews (PRs)
############################################
[context.deploy-preview]
  command = "pnpm install && hugo --gc --minify --buildFuture -b \"$HUGO_BASEURL\" && npx pagefind --source 'public'"

[context.deploy-preview.environment]
  # URL estable del preview (sin el hash de DEPLOY_URL). IMPORTANTE: barra final.
  HUGO_BASEURL = "$DEPLOY_PRIME_URL/"

############################################
# Branch deploys (main, staging, otras ramas)
############################################
[context.branch-deploy]
  command = "pnpm install && hugo --gc --minify -b \"$HUGO_BASEURL\" && npx pagefind --source 'public'"

[context.branch-deploy.environment]
  # ¡Clave! NO usar $URL aquí. Usar el subdominio del branch.
  HUGO_BASEURL = "$DEPLOY_PRIME_URL/"

############################################
# Plugins
############################################
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
