[build]
  command = "pnpm install && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  NODE_VERSION = "20.0.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "pnpm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "pnpm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

# --------- PROXIES PARA EL FEED DEL BLOG (evita CORS) ---------

# Usado por el blox rss-list en /blog/:
[[redirects]]
  from = "/blog/feed"
  to = "https://www.metadocencia.org/post/index.xml"
  status = 200
  force = true

# Alternativa/compatibilidad si alguien pide /blog/index.xml:
[[redirects]]
  from = "/blog/index.xml"
  to = "https://www.metadocencia.org/post/index.xml"
  status = 200
  force = true
