[build]
  command = "pnpm install && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  NODE_VERSION = "20.0.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "pnpm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "pnpm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

# ---- Functions ----
[functions]
  # (opcional) bundler moderno, por si lo necesitaras
  node_bundler = "esbuild"

# Proxy local del feed para evitar CORS:
[[redirects]]
  from = "/blog/feed"
  to = "/.netlify/functions/blog-feed"
  status = 200
  force = true

# Por si algún lector pide /blog/index.xml:
[[redirects]]
  from = "/blog/index.xml"
  to = "/.netlify/functions/blog-feed"
  status = 200
  force = true
